spring:
  application:
    name: connections-service
  neo4j:
    uri: neo4j://127.0.0.1:7687
    authentication:
      username: neo4j
      password: password@1234
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 9030
  servlet:
    context-path: /connections

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

