eureka.client:
  register-with-eureka: false
  fetch-registry: false

env:
  - name: CLOUDINARY_API_NAME
    valueFrom:
      secretKeyRef:
        name: cloudinary-secret
        key: api-name
  - name: CLOUDINARY_API_KEY
    valueFrom:
      secretKeyRef:
        name: cloudinary-secret
        key: api-key
  - name: CLOUDINARY_API_SECRET
    valueFrom:
      secretKeyRef:
        name: cloudinary-secret
        key: api-secret