spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/userDB
    username: postgres
    password: admin
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
